version: "3.3"
services:
  db:
    image: mongo:4.4.8
    volumes:
      - /mongodata:/data/db
    ports:
      - "27017:27017"
  ppblservice:
    build:
      context: ./ppblService
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    links:
      - db:database
  ppbl:
    build:
      context: ./ppbl
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - ppblservice:backendserverHOST
